openapi: 3.0.0
info:
  title: Project Management Application API
  description: MongoDB ExpressJS NodeJS REST API for the project management application
  version: 1.0.0
servers:
  - url: http://localhost:3000/api/ # live webserver location
    description: Localhost Development Server
components:
  securitySchemes:
    ApiKeyAuth:        # arbitrary name for the security scheme
      type: http
      scheme: bearer
      in: header       # can be "header", "query" or "cookie"
      name: auth-token

  schemas:
    Project:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        completed:
          type: boolean
        columns:
          type: object
          properties:
            col_name:
              type: string
            tasks:
              type: object
              properties:
                task_name:
                  type: string
                task_description:
                  type: string
                task_time:
                  type: number
                task_state:
                  type: string
                task_priority:
                  type: string
                asignee:
                  type: object
                  properties:
                owner:
                  type: object
                  properties:
                users:
                  type: object
                  properties:
                userRoles:
                  type: object
                  properties:
                    role:
                      type: string

    User:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        password:
          type: string

paths:

  /user/register:
    post:
      summary: Register a new User
      description: Register a new User in the database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"

      responses:
        201:
          description: User created succesfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /user/login:
    post:
      summary: Login a User
      description: Login a User in order to get JWT token (auth-token)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string

      responses:
        200:
          description: User logged in succesfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  data:
                    type: string


  /projects:
    get:
      summary: Retrieves a list of Projects created and associated to the account
      description: Retrieves a list of projects as JSON objects.
      security:
        - ApiKeyAuth: []
      responses:
        200:
          description: A list of projects JSON objects in an array.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Project"

    post:
      summary: Create a new Project
      description: Create a new Project
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                user:
                  type: string
                completed:
                  type: boolean
                columns:
                  type: object
                  properties:
                    col_name:
                      type: string
                    tasks:
                      type: object
                      properties:
                        task_name:
                          type: string
                        task_description:
                          type: string
                        task_time:
                          type: number
                        task_state:
                          type: string
                        task_priority:
                          type: string

      responses:
        201:
          description: Project created succesfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Project"

  /projects/{id}:
    get:
      summary: Specific Project
      description: Retrieve a specific Project based on its ID.
      security:
        - ApiKeyAuth: []
      parameters:
        - in: path
          name: id
          required: true
          description: MongoDB Project ObjectId
          schema:
            type: string
      responses:
        200:
          description: A Project in the format of a JSON object.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Project"

    put:
      summary: Updates a specific Project
      description: Updates a specific Project based on its ID.
      security:
        - ApiKeyAuth: []
      parameters:
        - in: path
          name: id
          required: true
          description: MongoDB Project ObjectId
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Project"

      responses:
        201:
          description: Project updated succesfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Project"

    delete:
      summary: Deletes a specific Project
      description: Deletes a specific Project based on its ObjectId.
      security:
        - ApiKeyAuth: []
      parameters:
        - in: path
          name: id
          required: true
          description: MongoDB Project ObjectId
          schema:
            type: string

      responses:
        201:
          description: Project deleted succesfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Project"

  /projects/deletecolumn/{id}:
    put:
      summary: Delete Specific card LIST in Project
      description: Delete Specific card LIST in Project by Column ID.
      security:
        - ApiKeyAuth: []
      parameters:
        - in: path
          name: id
          required: true
          description: MongoDB columns ObjectId
          schema:
            type: string
      responses:
        200:
          description: A Project in the format of a JSON object.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Project"